version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - SUPABASE_KEY=your-supabase-key
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
